### ISSUE TITLE
Blade syntax broken with VSCode 1.20.0 release

### ISSUE THREAD

**Issue by V-ed** [onecentlin/laravel-blade-snippets-vscode#42]
With the new VSCode update, things seems to be pretty broken with this extension right now as this screenshot suggests :
![blade syntax problem image](https://user-images.githubusercontent.com/16652915/35949069-bc3a2eca-0c3d-11e8-85cd-69c0d7e30741.png)

Here's the same screenshot with the PHP syntax enabled :
![correct syntax from php language](https://user-images.githubusercontent.com/16652915/35949093-d81b10b4-0c3d-11e8-9446-fc976d26f4fe.png)

Not only does this shows how the syntax is affected, this also means that other utilities are broken as well : snippets and autocompletion is also broken when you are located in the broken part of the syntax.
*Take note that this screenshot tries to show that the above snippet works, while the one in yellow show* `No suggestions`*.*
![snippet are also broken](https://user-images.githubusercontent.com/16652915/35949144-08ce0bda-0c3e-11e8-9024-217be85f60d6.png)

**Comment by jaumesala** [comment]
I confirm that. Maybe is problem of the emmet module? The following setting doesn't seems to work as expected, it should extend the html syntax but it doesn't do it:
```
"emmet.includeLanguages": {
   "blade": "html"
}
```

**Comment by mattyforth** [comment]
As a temporary solution you can add this to your settings until a fix comes out:

`
"files.associations": {
    "*.blade.php": "html"
}
`

No where near perfect but it just makes blade files use HTML syntax.

**Comment by izcream** [comment]
i got problem in vscode last version too

all html syntax gone wrong color
vscode 1.20.0

<img width="482" alt="screen shot 2018-02-08 at 16 58 56" src="https://user-images.githubusercontent.com/10282500/35966784-6b342634-0cf1-11e8-85cf-54df6f90a21e.png">

**Comment by rick2909** [comment]
so you have the same thing ass me and V-ed

**Comment by Naxes** [comment]
Can confirm, suffering the same issue. Updated this morning while working on a project.

**Comment by adrianriyadi** [comment]
hope in the next update for fix this issue, they also add javascript jquery auto completion within script tag just like in HTML and PHP files.

**Comment by elramus** [comment]
Yup same here, all fouled up.

**Comment by dan3460** [comment]
I thought it was only me, i see that i have company. I looked for other blade extensions but did not find any that i like. I hope this get fixed soon

**Comment by drehimself** [comment]
Same here, first thing I noticed when I updated a few days ago. Hopefully fixed soon, back to Sublime for now.

**Comment by onecentlin** [comment]
Just got home from vacation. I'll take a look see if I can fix the issue soon.

**Comment by lxlkuc** [comment]
同样问题，也是因为vscode更新到1.20。

**Comment by alexfonseka** [comment]
Same here :/

**Comment by ariefadjie** [comment]
While, I switched to https://github.com/cjhowe7/laravel-blade-vscode

**Comment by V-ed** [comment]
@ariefadjie I was skeptical about this extension since the issue cjhowe7/laravel-blade-vscode#1 is currently opened, but I tried it nonetheless and this one does work.

Keep in mind that this means you will need to disable @onecentlin's extension as it uses the same language id (`blade`) for the syntax, so that'll make a conflict. That also means loosing the snippets, but personally, the syntax is more important - you'll need to see if it works for your setup.

Well, this is working out for now - thanks @ariefadjie!

**Comment by jurgentreep** [comment]
Seems to take a bit long so I also switched to https://marketplace.visualstudio.com/items?itemName=cjhowe7.laravel-blade

**Comment by tiansin** [comment]
Excessive version:[laravel-blade-1.13.0.zip](https://github.com/tiansin/laravel-blade-snippets-vscode/files/1725260/laravel-blade-1.13.0.zip)

**Comment by V-ed** [comment]
@tiansin Awesome! Seems to work pretty good so far, maybe doing a pull request of the changes to @onecentlin would help him push this update faster for everyone relying on this extension!

I had to lookup how to install vsix extension and [found Microsoft's documention here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) (for anyone wondering how to install it). Make sure @onecentlin's extension is uninstalled before installing @tiansin's temporary solution!

Thanks alot, I missed the snippets of this extension :)

**Comment by tiansin** [comment]
@V-ed 
Now there is a more important update, hoping to participate in the test, an increase of support for the style of the view file and script auto-completion, and support jquery
[laravel-blade-1.13.0.vsix](https://github.com/tiansin/laravel-blade-snippets-vscode/releases/tag/1.1.3)

**Comment by adrianriyadi** [comment]
oh wow, dude.. this is what I'm talking about for few months. I really glad if this included in the next update @onecentlin.. really appreciate that @tiansin :)

**Comment by V-ed** [comment]
@tiansin Looks like an awesome update that you did there, although the link you provided links to your previous version (which again is already neat!), and I don't have what's required to build your source code on my machine - I'll look into it later if you won't already have done it.

Thanks alot for your work on this extension, my workflow is greatly enhanced because of you!

**Comment by onecentlin** [comment]
@tiansin Thanks for your excellent contribution. I merged #43 pull request. However, there are some issues with `server/out/htmlServerMain.js`. Would you please help me out?

**Comment by tiansin** [comment]
@onecentlin 
I guess it may not compile the server code,
Add the following steps to try.
step1:
cd server
step2:
npm install
step3
tsc

**Comment by tiansin** [comment]
![bug](https://user-images.githubusercontent.com/4232281/36302746-922364ae-1344-11e8-89a4-96ebdb5b092b.png)

I found in the 1.14.0 plugin directory, lost server code

**Comment by V-ed** [comment]
@tiansin's fix has been pushed to @onecentlin's branch with the fix included to resolve this issue.

The discussion about server problems can be discussed in the relevant issue (#44).

Another big thanks to @tiansin! :)

**Comment by mykeels** [comment]
For me, this happened because I had conflicting Laravel Blade Snippet extensions. 

I uninstalled them all, and re-installed https://github.com/onecentlin/laravel-blade-snippets-vscode.

It's fixed now.

**Comment by chrisreedio** [comment]
I'm still having this issue with regards to javascript intellisense is broken. 

I have made sure that I have no other 'blade' extensions. 

I tried to use @tiansin's version but it had errors in the console upon loading. Probably because it's so old at this point?

If I change the language type to PHP or HTML then all of the javascript and jQuery intellisense works. 

Any thoughts or ideas for things I can try? 

Thanks for your time and for writing a great extension!
